FileUploadOnAWSProject/FileUploadOnAWSProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('home.urls', 'home'), namespace='home_app_link')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts_app_link')),
    path('posts/', include(('upload_posts.urls', 'upload_posts'), namespace='upload_posts_app_link')),
]

FileUploadOnAWSProject/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_login

urlpatterns = [
    path('registration/', views.AccountRegistrationView.as_view(), name="account_registration"),

    path('login/', auth_login.LoginView.as_view(template_name='accounts/login.html'), name="account_login"),

    path('logout/', auth_login.LogoutView.as_view(), name="account_logout"),

]

FileUploadOnAWSProject/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_login

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),

]

FileUploadOnAWSProject/upload_posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('upload/', views.UploadPostsView.as_view(), name="upload_posts"),

    path('view-posts/<str:id>', views.ViewPostsView.as_view(), name="view_posts"),

    path('view-own-posts/', views.ViewOwnPostsView.as_view(), name="view_own_posts"),

]

FileUploadOnAWSProject/accounts/models.py
from django.db import models

# Create your models here.

FileUploadOnAWSProject/home/models.py
from django.db import models

# Create your models here.

FileUploadOnAWSProject/upload_posts/models.py
from django.db import models
import uuid
from django.utils.translation import ugettext_lazy
from autoslug import AutoSlugField
import django
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save


class Posts(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(ugettext_lazy('Title'), max_length=100, db_column="title")
    slug = AutoSlugField(populate_from='title', always_update=True, unique_with='created_at__month', db_column="slug",
                         null=True, blank=True)
    file = models.FileField()
    url = models.CharField(ugettext_lazy('Post Url'), max_length=100, null=True, blank=True, db_column="url")
    status = models.BooleanField(ugettext_lazy('Status'), default=True, db_column="status")
    created_at = models.DateTimeField(default=django.utils.timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="posts_user")

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name_plural = 'Posts'
        db_table = 'Posts'


def post_save_create_url(sender, instance, *args, **kwargs):
    if not instance.url:
        instance.url = settings.BASE_URL + 'posts/view-posts/' + str(instance.id)


post_save.connect(post_save_create_url, sender=Posts)

FileUploadOnAWSProject/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label="First Name", widget=forms.TextInput(attrs={"placeholder": "First Name"}))
    last_name = forms.CharField(label="Last Name", widget=forms.TextInput(attrs={"placeholder": "Last Name"}))
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"placeholder": "Username"}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}))
    email = forms.EmailField(label="Email Address", max_length=254, help_text='Email.',widget=forms.TextInput(attrs={"placeholder": "E-mail"}))

    class Meta:
        model = User
        fields = ('first_name','last_name','username', 'email', 'password1', 'password2', )

FileUploadOnAWSProject/upload_posts/forms.py
from django import forms
from .models import Posts


class PostsForm(forms.ModelForm):
    title = forms.CharField(label="Name", widget=forms.TextInput(attrs={"placeholder": "Posts Name"}))
    file = forms.FileField(label="File", widget=forms.FileInput(attrs={"placeholder": "Posts File"}))

    class Meta:
        model = Posts
        fields = ('title', 'file')

FileUploadOnAWSProject/accounts/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import SignUpForm
from django.views import generic
from django.contrib import messages
from django.urls import reverse


class AccountRegistrationView(generic.View):
    user_form = SignUpForm

    def get(self,request):
        return render(request,"accounts/registration.html", {"user_form":self.user_form})

    def post(self, request):
        post_data = request.POST or None

        user_form = self.user_form(post_data)
        if user_form.is_valid():
            new_user = user_form.save()
            messages.info(request, 'A Verification code has been sent to your email id. :- ' + new_user.email)
            return HttpResponseRedirect(reverse('home_app_link:home'))
        else:
            messages.error(request, user_form.errors)
        return HttpResponseRedirect(reverse('accounts_app_link:account_login'))

FileUploadOnAWSProject/home/views.py
from django.shortcuts import render
from django.views import generic


class HomeView(generic.View):

    def get(self,request,  *args, **kwargs):

        return render(request,"home/index.html")

FileUploadOnAWSProject/upload_posts/views.py
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from .models import Posts
from .forms import PostsForm
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages


@method_decorator(login_required , name="dispatch")
class UploadPostsView(SuccessMessageMixin, generic.CreateView):
    form_class = PostsForm
    template_name = 'upload_posts/create_posts.html'

    def get_success_message(self, cleaned_data):
        return "Posts created."

    def get_context_data(self, *args, **kwargs):
        context = super(UploadPostsView, self).get_context_data(*args, **kwargs)
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return HttpResponseRedirect(reverse('upload_posts_app_link:view_own_posts'))

    def form_invalid(self, form):
        messages.error(self.request, form.errors)
        return HttpResponseRedirect(reverse('upload_posts_app_link:upload_posts'))


class ViewPostsView(generic.TemplateView):
    template_name = 'upload_posts/view_posts.html'

    def get_context_data(self, id, *args, **kwargs):
        context = super(ViewPostsView, self).get_context_data(*args, **kwargs)
        context['posts_data'] = get_object_or_404(Posts, id=id)
        return context


@method_decorator(login_required , name="dispatch")
class ViewOwnPostsView(SuccessMessageMixin, generic.ListView):
    model = Posts
    template_name = 'upload_posts/index.html'
    context_object_name = 'posts_data'
    paginate_by = 2
    queryset = None

    def get_context_data(self, *args,**kwargs):
        context = super(ViewOwnPostsView, self).get_context_data(*args, **kwargs)
        return context

    def get_queryset(self,**kwargs):
        get_data = Posts.objects.filter(created_by=self.request.user).order_by("-id")
        return get_data

FileUploadOnAWSProject/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>FileUploadOnAWS</title>
   </head>
   <body>
      <h3>{% if request.user.is_anonymous == False %}Welcome {{request.user}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:upload_posts' %}">  Create Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:view_own_posts' %}">  My Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_logout' %}">  Logout</a>&nbsp;&nbsp;&nbsp;&nbsp;{% else %}<a href="{% url 'accounts_app_link:account_registration' %}">  Registration</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_login' %}">  Login</a>&nbsp;&nbsp;&nbsp;&nbsp; 
         {% endif %}
      </h3>
      <br>
      <br>
      {% if messages %}
      {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      {{message}}
      {% endif %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      {{message}}
      {% endif %}
      {% endfor %}
      {% endif %}
      <div style="text-align: center;">
         <form method="POST" action="#">
            {% csrf_token %}
            <h2 class="signin">Create An Account</h2>
            <label>Username : </label>
            {{form.username}}<br><br>
            <label>Password : </label>
            {{form.password}}<br><br>
            <button type="submit" class="btn btn-outline-dark sign-in">Sign In</button>
         </form>
      </div>
   </body>
</html>

FileUploadOnAWSProject/accounts/templates/accounts/registration.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>FileUploadOnAWS</title>
   </head>
   <body>
      <h3>{% if request.user.is_anonymous == False %}Welcome {{request.user}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:upload_posts' %}">  Create Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:view_own_posts' %}">  My Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_logout' %}">  Logout</a>&nbsp;&nbsp;&nbsp;&nbsp;{% else %}<a href="{% url 'accounts_app_link:account_registration' %}">  Registration</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_login' %}">  Login</a>&nbsp;&nbsp;&nbsp;&nbsp; 
         {% endif %}
      </h3>
      <br>
      <br>
      {% if messages %}
      {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      {{message}}
      {% endif %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      {{message}}
      {% endif %}
      {% endfor %}
      {% endif %}
      <!-- message Stop -->
      <form method="POST" action="#">
         {% csrf_token %}
         <h3 class="signin">Create An Account</h3>
         {{user_form.first_name}}<br><br>
         {{user_form.last_name}}<br><br>
         {{user_form.username}}<br><br>
         {{user_form.email}}<br><br>
         {{user_form.password1}}<br><br>
         {{user_form.password2}}<br><br>
         <button type="submit" class="btn btn-outline-dark sign-in">Sign Up</button>
      </form>
   </body>
</html>

FileUploadOnAWSProject/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>FileUploadOnAWS</title>
   </head>
   <body>
      <h3>{% if request.user.is_anonymous == False %}Welcome {{request.user}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:upload_posts' %}">  Create Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:view_own_posts' %}">  My Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_logout' %}">  Logout</a>&nbsp;&nbsp;&nbsp;&nbsp;{% else %}<a href="{% url 'accounts_app_link:account_registration' %}">  Registration</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_login' %}">  Login</a>&nbsp;&nbsp;&nbsp;&nbsp; 
         {% endif %}
      </h3>
      <br>
      <br>
      {% if messages %}
      {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      {{message}}
      {% endif %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      {{message}}
      {% endif %}
      {% endfor %}
      {% endif %}
      <h1 style="text-align: center;">Welcome to Test Project...</h1>
   </body>
</html>

FileUploadOnAWSProject/upload_posts/templates/upload_posts/create_posts.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>FileUploadOnAWS</title>
   </head>
   <body>
      <h3>{% if request.user.is_anonymous == False %}Welcome {{request.user}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:upload_posts' %}">  Create Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:view_own_posts' %}">  My Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_logout' %}">  Logout</a>&nbsp;&nbsp;&nbsp;&nbsp;{% else %}<a href="{% url 'accounts_app_link:account_registration' %}">  Registration</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_login' %}">  Login</a>&nbsp;&nbsp;&nbsp;&nbsp; 
         {% endif %}
      </h3>
      <br>
      <br>
      {% if messages %}
      {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      {{message}}
      {% endif %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      {{message}}
      {% endif %}
      {% endfor %}
      {% endif %}
      <!-- message Stop -->
      <form method="POST" action="#"  enctype="multipart/form-data">
         {% csrf_token %}
         <h3 class="signin">Create An Account</h3>
         {{form.title}}<br><br>
         {{form.file}}<br><br>
         <button type="submit" class="btn btn-outline-dark sign-in">Upload</button>
      </form>
   </body>
</html>

FileUploadOnAWSProject/upload_posts/templates/upload_posts/index.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>FileUploadOnAWS</title>
      <style>
         table {
         font-family: arial, sans-serif;
         border-collapse: collapse;
         width: 100%;
         }
         td, th {
         border: 1px solid #dddddd;
         text-align: left;
         padding: 8px;
         }
         tr:nth-child(even) {
         background-color: #dddddd;
         }
         ul.pagination.justify-content-center {
         padding: 0;
         display: flex;
         align-items: center;
         justify-content: right;
         }
         span.span-number {
         margin: 0 10px;
         }
         ul.pagination.justify-content-center li {
         list-style: none;
         margin: 0 10px;
         }
      </style>
   </head>
   <body>
      <h3>{% if request.user.is_anonymous == False %}Welcome {{request.user}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:upload_posts' %}">  Create Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:view_own_posts' %}">  My Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_logout' %}">  Logout</a>&nbsp;&nbsp;&nbsp;&nbsp;{% else %}<a href="{% url 'accounts_app_link:account_registration' %}">  Registration</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_login' %}">  Login</a>&nbsp;&nbsp;&nbsp;&nbsp; 
         {% endif %}
      </h3>
      <br>
      <br>
      {% if messages %}
      {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      {{message}}
      {% endif %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      {{message}}
      {% endif %}
      {% endfor %}
      {% endif %}
      <h2 style="text-align: center;">Posts Detail</h2>
      <br>
      <table>
         <tr>
            <th style="text-align: center;">S. No.</th>
            <th style="text-align: center;">Name</th>
            <th style="text-align: center;">Post Url</th>
            <th style="text-align: center;">Image</th>
         </tr>
         {% for data in posts_data %}
         <tr>
            <td>{{forloop.counter}}</td>
            <td>{{data.title}}</td>
            <td style="text-align: center;"><a href="{{data.url}}">View Post</a></td>
            <td style="text-align: center;">{% if data.file %}<img src="{{data.file.url}}"  style="width: 100px; height: 100px;">{% else %}No File{% endif %}</td>
         </tr>
         {% endfor %}
      </table>
      <nav aria-label="Page navigation " class="supplier-pagination">
         {% if is_paginated %}
         <ul class="pagination  justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item"><a  class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><span class="span-number">Previous</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active"><span class="span-number">{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li><a  class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a  class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><span class="span-number">Next</span></li>
            {% endif %}
         </ul>
         {% endif %}
      </nav>
   </body>
</html>

FileUploadOnAWSProject/upload_posts/templates/upload_posts/view_posts.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>FileUploadOnAWS</title>
   </head>
   <body>
      <h3>{% if request.user.is_anonymous == False %}Welcome {{request.user}}&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:upload_posts' %}">  Create Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'upload_posts_app_link:view_own_posts' %}">  My Posts</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_logout' %}">  Logout</a>&nbsp;&nbsp;&nbsp;&nbsp;{% else %}<a href="{% url 'accounts_app_link:account_registration' %}">  Registration</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts_app_link:account_login' %}">  Login</a>&nbsp;&nbsp;&nbsp;&nbsp; 
         {% endif %}
      </h3>
      <br>
      <br>
      {% if messages %}
      {% for message in messages %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
      {{message}}
      {% endif %}
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      {{message}}
      {% endif %}
      {% endfor %}
      {% endif %}
      <div style="text-align: right;">
         <h3>Created by: <span>Radhe</span></h3>
      </div>
      <div style="text-align: center;">
         <img src="{{posts_data.file.url}}" style="    width: 50%;">
      </div>
      <span style="text-align: center;">
         <h3>{{posts_data.title}}</h3>
      </span>
   </body>
</html>